blist = ["china", "bhutan" , 'nepal' , "siberia" , "afganistan"]
print(blist)
print(sorted(blist))
print(blist)
print(sorted(blist , reverse = True))
print(blist)
blist.reverse()
print(blist)
blist.reverse()
print(blist)
blist.sort()
print(blist)
blist.sort(reverse = True)
print(blist)
print(len(blist))